language: java
jdk:
  - openjdk11

branches:
  only:
    - main

#현재 위치로부터 프로젝트 빌드를 진행할 곳으로 이동
#before_script:
#  - cd chevita-Backend/

# Travis CI 서버의 Cache 활성화
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

#travis CI에서 빌드한 jar 파일을 s3에 올리는 코드
before_deploy:
  - zip -r chevita-Backend * #프로젝트 이름이라는데 정확히 어떤걸 얘기하는지 모르겠음 일단 github에 올려둔 이름으로 함
  - mkdir -p deploy
  - mv chevita-Backend.zip deploy/chevita-Backend.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: chevita-bucket #버킷이름 : chevita-bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private #zip 파일 접근 private으로
    local_dir: deploy #before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

    on:
      branch: main #main에만 권한 부여

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY #Travis repo settingd에 설정된 값
    secret_access_key: $AWS_SECRET_KEY

    bucket: chevita-bucket #S3 버킷
    key: chevita-backend.zip #빌드 파일 압축해서 전달
    bundle_type: zip
    application: CodeDeployGitHubChevita-App #웹 콘솔에서 등록한 codedeploy 애플리케이션

    deployment_group: CodeDeployGitHubChevita-DepGrp # 웹 콘솔에서 등록한 codedeploy 배포 그룹

    region: ap-northeast-2
    wait-until-deployed: true
#    all_branches: true #master 브랜치 외 다른 브랜치에도 권한 부여



# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - susu19@ewhain.net
      - doooheun@gmail.com

