cloud:
  aws:
    credentials:
      access-key: AKIATKZDLSS4WWPLSIGT
      secret-key: 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
    s3:
      bucket: chevita-bucket
    region:
      static: ap-northeast-2 # 리전 정보
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error